
services:
  marketplace_postgres:
    container_name: marketplace_postgres
    image: postgres:16
    environment:
      POSTGRES_USER: marketplace
      POSTGRES_PASSWORD: marketplace
      PGDATA: /data/postgres
    volumes:
       - postgres:/var/www/marketplace/docker-volumes/postgres
    ports:
      - 127.0.0.1:5433:5432
    networks:
      - marketplace
    restart: unless-stopped

  marketplace_pgadmin:
    container_name: marketplace_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: marketplace@admin.com
      PGADMIN_DEFAULT_PASSWORD: marketplace
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/www/marketplace/docker-volumes/pgadmin
    ports:
      - 127.0.0.1:5050:80
    networks:
      - marketplace
    restart: unless-stopped

  marketplace_rabbitmq:
    container_name: marketplace_rabbitmq
    image: rabbitmq:3.13-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: marketplace
      RABBITMQ_DEFAULT_PASS: marketplace
      RABBITMQ_DEFAULT_VHOST: marketplace_vhost
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    ports:
      - 127.0.0.1:5672:5672   # AMQP protocol
      - 127.0.0.1:15672:15672 # Management UI
    networks:
      - marketplace
    restart: unless-stopped
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  marketplace:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  rabbitmq: